#ifndef PO_SETTINGS_H
#define PO_SETTINGS_H

#ifndef MIDI_SETTINGS_H
#include "midi_settings.h"
#endif



//Teensy GPIO mapping to PO button
#define PO_BUTTON_1 5
#define PO_BUTTON_2 6
#define PO_BUTTON_3 19
#define PO_BUTTON_4 18
#define PO_BUTTON_5 10
#define PO_BUTTON_6 11
#define PO_BUTTON_7 14
#define PO_BUTTON_8 15
#define PO_BUTTON_9 25
#define PO_BUTTON_10 12
#define PO_BUTTON_11 39
#define PO_BUTTON_12 38
#define PO_BUTTON_13 30
#define PO_BUTTON_14 32
#define PO_BUTTON_15 34
#define PO_BUTTON_16 33
#define PO_BUTTON_SOUND 2
#define PO_BUTTON_PATTERN 3
#define PO_BUTTON_WRITE 35
#define PO_BUTTON_PLAY 36
#define PO_BUTTON_FX 16
#define PO_BUTTON_BPM 23
#define PO_BUTTON_SPECIAL 17
#define PO_POT_A 22
#define PO_POT_B 21

#define CLOCKSYNCPIN A21

uint8_t note_map[23][2] = {
  {MIDI_NOTE_1,PO_BUTTON_9},
  {MIDI_NOTE_2,PO_BUTTON_10},
  {MIDI_NOTE_3,PO_BUTTON_11},
  {MIDI_NOTE_4,PO_BUTTON_12},
  {MIDI_NOTE_5,PO_BUTTON_13},
  {MIDI_NOTE_6,PO_BUTTON_14},
  {MIDI_NOTE_7,PO_BUTTON_15},
  {MIDI_NOTE_8,PO_BUTTON_16},
  {MIDI_NOTE_9,PO_BUTTON_1},
  {MIDI_NOTE_10,PO_BUTTON_2},
  {MIDI_NOTE_11,PO_BUTTON_3},
  {MIDI_NOTE_12,PO_BUTTON_4},
  {MIDI_NOTE_13,PO_BUTTON_5},
  {MIDI_NOTE_14,PO_BUTTON_6},
  {MIDI_NOTE_15,PO_BUTTON_7},
  {MIDI_NOTE_16,PO_BUTTON_8},
  {MIDI_NOTE_17,PO_BUTTON_SOUND},
  {MIDI_NOTE_18,PO_BUTTON_PATTERN},
  {MIDI_NOTE_19,PO_BUTTON_BPM},
  {MIDI_NOTE_20,PO_BUTTON_SPECIAL},
  {MIDI_NOTE_21,PO_BUTTON_FX},
  {MIDI_NOTE_22,PO_BUTTON_PLAY},
  {MIDI_NOTE_23,PO_BUTTON_WRITE},
};


uint8_t transport_note_map[7][2] ={
  {MIDI_NOTE_9,PO_BUTTON_SOUND},
  {MIDI_NOTE_10,PO_BUTTON_PATTERN},
  {MIDI_NOTE_11,PO_BUTTON_BPM},
  {MIDI_NOTE_1,PO_BUTTON_SPECIAL},
  {MIDI_NOTE_2,PO_BUTTON_FX},
  {MIDI_NOTE_3,PO_BUTTON_PLAY},
  {MIDI_NOTE_4,PO_BUTTON_WRITE}
};

#define PERF_MODE 0
#define NORMAL_MODE 1
#define FX_MODE 2
#define RECORD_MODE 3
#define WRITE_MODE 4

#endif